// Generated by gencpp from file turtlesim_halbeisen/LogTimeoutRequest.msg
// DO NOT EDIT!


#ifndef TURTLESIM_HALBEISEN_MESSAGE_LOGTIMEOUTREQUEST_H
#define TURTLESIM_HALBEISEN_MESSAGE_LOGTIMEOUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_halbeisen
{
template <class ContainerAllocator>
struct LogTimeoutRequest_
{
  typedef LogTimeoutRequest_<ContainerAllocator> Type;

  LogTimeoutRequest_()
    : timeout(0)  {
    }
  LogTimeoutRequest_(const ContainerAllocator& _alloc)
    : timeout(0)  {
  (void)_alloc;
    }



   typedef int64_t _timeout_type;
  _timeout_type timeout;





  typedef boost::shared_ptr< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LogTimeoutRequest_

typedef ::turtlesim_halbeisen::LogTimeoutRequest_<std::allocator<void> > LogTimeoutRequest;

typedef boost::shared_ptr< ::turtlesim_halbeisen::LogTimeoutRequest > LogTimeoutRequestPtr;
typedef boost::shared_ptr< ::turtlesim_halbeisen::LogTimeoutRequest const> LogTimeoutRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator1> & lhs, const ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator2> & rhs)
{
  return lhs.timeout == rhs.timeout;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator1> & lhs, const ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlesim_halbeisen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3dac15c934c0b4b7e2dacd84bb5ff9fe";
  }

  static const char* value(const ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3dac15c934c0b4b7ULL;
  static const uint64_t static_value2 = 0xe2dacd84bb5ff9feULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_halbeisen/LogTimeoutRequest";
  }

  static const char* value(const ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 timeout\n"
;
  }

  static const char* value(const ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LogTimeoutRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_halbeisen::LogTimeoutRequest_<ContainerAllocator>& v)
  {
    s << indent << "timeout: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_HALBEISEN_MESSAGE_LOGTIMEOUTREQUEST_H
