// Generated by gencpp from file turtlesim_halbeisen/StopControl.msg
// DO NOT EDIT!


#ifndef TURTLESIM_HALBEISEN_MESSAGE_STOPCONTROL_H
#define TURTLESIM_HALBEISEN_MESSAGE_STOPCONTROL_H

#include <ros/service_traits.h>


#include <turtlesim_halbeisen/StopControlRequest.h>
#include <turtlesim_halbeisen/StopControlResponse.h>


namespace turtlesim_halbeisen
{

struct StopControl
{

typedef StopControlRequest Request;
typedef StopControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopControl
} // namespace turtlesim_halbeisen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim_halbeisen::StopControl > {
  static const char* value()
  {
    return "e90fd0c296d28562ef619e70f6278695";
  }

  static const char* value(const ::turtlesim_halbeisen::StopControl&) { return value(); }
};

template<>
struct DataType< ::turtlesim_halbeisen::StopControl > {
  static const char* value()
  {
    return "turtlesim_halbeisen/StopControl";
  }

  static const char* value(const ::turtlesim_halbeisen::StopControl&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim_halbeisen::StopControlRequest> should match
// service_traits::MD5Sum< ::turtlesim_halbeisen::StopControl >
template<>
struct MD5Sum< ::turtlesim_halbeisen::StopControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_halbeisen::StopControl >::value();
  }
  static const char* value(const ::turtlesim_halbeisen::StopControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_halbeisen::StopControlRequest> should match
// service_traits::DataType< ::turtlesim_halbeisen::StopControl >
template<>
struct DataType< ::turtlesim_halbeisen::StopControlRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim_halbeisen::StopControl >::value();
  }
  static const char* value(const ::turtlesim_halbeisen::StopControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim_halbeisen::StopControlResponse> should match
// service_traits::MD5Sum< ::turtlesim_halbeisen::StopControl >
template<>
struct MD5Sum< ::turtlesim_halbeisen::StopControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_halbeisen::StopControl >::value();
  }
  static const char* value(const ::turtlesim_halbeisen::StopControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_halbeisen::StopControlResponse> should match
// service_traits::DataType< ::turtlesim_halbeisen::StopControl >
template<>
struct DataType< ::turtlesim_halbeisen::StopControlResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim_halbeisen::StopControl >::value();
  }
  static const char* value(const ::turtlesim_halbeisen::StopControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_HALBEISEN_MESSAGE_STOPCONTROL_H
