// Generated by gencpp from file turtlesim_halbeisen/StopControlRequest.msg
// DO NOT EDIT!


#ifndef TURTLESIM_HALBEISEN_MESSAGE_STOPCONTROLREQUEST_H
#define TURTLESIM_HALBEISEN_MESSAGE_STOPCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_halbeisen
{
template <class ContainerAllocator>
struct StopControlRequest_
{
  typedef StopControlRequest_<ContainerAllocator> Type;

  StopControlRequest_()
    : is_publishing(false)  {
    }
  StopControlRequest_(const ContainerAllocator& _alloc)
    : is_publishing(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_publishing_type;
  _is_publishing_type is_publishing;





  typedef boost::shared_ptr< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopControlRequest_

typedef ::turtlesim_halbeisen::StopControlRequest_<std::allocator<void> > StopControlRequest;

typedef boost::shared_ptr< ::turtlesim_halbeisen::StopControlRequest > StopControlRequestPtr;
typedef boost::shared_ptr< ::turtlesim_halbeisen::StopControlRequest const> StopControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator1> & lhs, const ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.is_publishing == rhs.is_publishing;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator1> & lhs, const ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlesim_halbeisen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3cd757ae264dd63b16b775844045c5e";
  }

  static const char* value(const ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3cd757ae264dd63ULL;
  static const uint64_t static_value2 = 0xb16b775844045c5eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_halbeisen/StopControlRequest";
  }

  static const char* value(const ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_publishing\n"
;
  }

  static const char* value(const ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_publishing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_halbeisen::StopControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "is_publishing: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_publishing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_HALBEISEN_MESSAGE_STOPCONTROLREQUEST_H
