(cl:defpackage turtlesim_halbeisen-srv
  (:use )
  (:export
   "LOGTIMEOUT"
   "<LOGTIMEOUT-REQUEST>"
   "LOGTIMEOUT-REQUEST"
   "<LOGTIMEOUT-RESPONSE>"
   "LOGTIMEOUT-RESPONSE"
   "STOPCONTROL"
   "<STOPCONTROL-REQUEST>"
   "STOPCONTROL-REQUEST"
   "<STOPCONTROL-RESPONSE>"
   "STOPCONTROL-RESPONSE"
  ))

