# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtlesim_halbeisen/TurtlesimState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import turtlesim.msg

class TurtlesimState(genpy.Message):
  _md5sum = "7c35fa8e2a3f6d67a17abc9bc29d508c"
  _type = "turtlesim_halbeisen/TurtlesimState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """turtlesim/Pose pose
turtlesim/Color color
geometry_msgs/Twist twist
================================================================================
MSG: turtlesim/Pose
float32 x
float32 y
float32 theta

float32 linear_velocity
float32 angular_velocity
================================================================================
MSG: turtlesim/Color
uint8 r
uint8 g
uint8 b

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['pose','color','twist']
  _slot_types = ['turtlesim/Pose','turtlesim/Color','geometry_msgs/Twist']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose,color,twist

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TurtlesimState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pose is None:
        self.pose = turtlesim.msg.Pose()
      if self.color is None:
        self.color = turtlesim.msg.Color()
      if self.twist is None:
        self.twist = geometry_msgs.msg.Twist()
    else:
      self.pose = turtlesim.msg.Pose()
      self.color = turtlesim.msg.Color()
      self.twist = geometry_msgs.msg.Twist()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f3B6d().pack(_x.pose.x, _x.pose.y, _x.pose.theta, _x.pose.linear_velocity, _x.pose.angular_velocity, _x.color.r, _x.color.g, _x.color.b, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = turtlesim.msg.Pose()
      if self.color is None:
        self.color = turtlesim.msg.Color()
      if self.twist is None:
        self.twist = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 71
      (_x.pose.x, _x.pose.y, _x.pose.theta, _x.pose.linear_velocity, _x.pose.angular_velocity, _x.color.r, _x.color.g, _x.color.b, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z,) = _get_struct_5f3B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f3B6d().pack(_x.pose.x, _x.pose.y, _x.pose.theta, _x.pose.linear_velocity, _x.pose.angular_velocity, _x.color.r, _x.color.g, _x.color.b, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = turtlesim.msg.Pose()
      if self.color is None:
        self.color = turtlesim.msg.Color()
      if self.twist is None:
        self.twist = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 71
      (_x.pose.x, _x.pose.y, _x.pose.theta, _x.pose.linear_velocity, _x.pose.angular_velocity, _x.color.r, _x.color.g, _x.color.b, _x.twist.linear.x, _x.twist.linear.y, _x.twist.linear.z, _x.twist.angular.x, _x.twist.angular.y, _x.twist.angular.z,) = _get_struct_5f3B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f3B6d = None
def _get_struct_5f3B6d():
    global _struct_5f3B6d
    if _struct_5f3B6d is None:
        _struct_5f3B6d = struct.Struct("<5f3B6d")
    return _struct_5f3B6d
